name: Easy_Structures
main: dkramer.WorldFeatures
version: 0.10
author: Easy_Structures
load: startup
description: A plugin to spread custom schematics throughout your world.
website: https://github.com/navett52/Easy_Structures
commands:
  populate:
    description: Re-populates chunks that haven't been populated by the plugin
permissions: