name: WorldSchematics
main: dkramer.WorldFeatures
version: 1.0
author: WorldSchematics
load: startup
description: Generates .schematics into generated chunks.
website: http://cantripsandcooldowns.wordpress.com
commands:
    ws:
        description: Use this to display the other commands.
        usage: /ws
    WorldSchematics:
        description: Use this to display the other commands.
        usage: /WorldSchematics
permissions:
    WorldSchematics.commands:
        description: Gives permission to use every command.